In [0]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.1-py2.py3-none-any.whl (249 kB)
     |████████████████████████████████| 249 kB 5.5 MB/s
Collecting et-xmlfile
  Downloading et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-1.1.0 openpyxl-3.1.1
WARNING: You are using pip version 21.2.4; however, version 23.0 is available.
You should consider upgrading via the '/local_disk0/.ephemeral_nfs/envs/pythonEnv-5493f8f7-6171-4945-bc64-1147dbd1391a/bin/python -m pip install --upgrade pip' command.

In [0]:
import pyspark.pandas as pd

filename= "demo.xlsx"
folder= 'dbfs:/FileStore/shared_uploads/Ravi.Ranjan9@cognizant.com/'
url= folder + filename

read= pd.read_excel(url, sheet_name='Sheet1')

df= read.to_spark()



#read="dbfs:/FileStore/shared_uploads/Ravi.Ranjan9@cognizant.com/demo.xlsx"

/databricks/spark/python/pyspark/pandas/namespace.py:1126: FutureWarning: convert_float is deprecated and will be removed in a future version
  return pd.read_excel(

In [0]:
'''from pyspark.sql import SparkSession
spark= SparkSession.builder.appName('chatbot').getOrCreate()'''
'''from pyspark.sql.functions import col

closed_status_df = df.filter(col("Status") == "Closed")
closed_status_df.select("Field Name").show()'''

Out[6]: 'from pyspark.sql.functions import col\n\nclosed_status_df = df.filter(col("Status") == "Closed")\nclosed_status_df.select("Field Name").show()'

In [0]:
display(df)

Object name 2004 R2,Field Name,LIMS 12.3 Object Name,LIMS 12.3 Column Name,Status,Comments/Query
A_BUILDING,A_SITE,LOCATION,PARENT_LOCATION,Closed,SELECT DISTINCT PARENT_LOCATION FROM LOCATION ORDER BY GROUP_ID DESC;
A_BUILDING,DESCRIPTION,LOCATION,DESCRIPTION,Closed,SELECT DISTINCT PARENT_LOCATION FROM LOCATION ORDER BY GROUP_ID DESC;
A_BUILDING,GROUP_ID,LOCATION,GROUP_ID,Closed,SELECT DISTINCT PARENT_LOCATION FROM LOCATION ORDER BY GROUP_ID DESC;
A_BUILDING,IDENTITY,LOCATION,IDENTITY,Closed,SELECT DISTINCT PARENT_LOCATION FROM LOCATION ORDER BY GROUP_ID DESC;
A_BUILDING,MODIFIABLE,LOCATION,MODIFIABLE,Closed,SELECT DISTINCT PARENT_LOCATION FROM LOCATION ORDER BY GROUP_ID DESC;
A_BUILDING,MODIFIED_BY,LOCATION,MODIFIED_BY,Closed,SELECT DISTINCT PARENT_LOCATION FROM LOCATION ORDER BY GROUP_ID DESC;
A_BUILDING,MODIFIED_ON,LOCATION,MODIFIED_ON,Closed,SELECT DISTINCT PARENT_LOCATION FROM LOCATION ORDER BY GROUP_ID DESC;
A_BUILDING,REMOVEFLAG,LOCATION,REMOVEFLAG,Closed,SELECT DISTINCT PARENT_LOCATION FROM LOCATION ORDER BY GROUP_ID DESC;
A_ERD_SP_BUILDING,BUILDING,null,null,Consolidation not required,No Mapping
A_ERD_SP_BUILDING,ERD_OFFSET,null,null,Consolidation not required,No Mapping
A_ERD_SP_BUILDING,REMOVEFLAG,null,null,Consolidation not required,No Mapping
A_ERD_SP_BUILDING,SAMPLING_POINT,null,null,Consolidation not required,No Mapping
A_LAB,A_BUILDING,LOCATION,PARENT_LOCATION,Closed,SELECT DISTINCT PARENT_LOCATION FROM LOCATION ORDER BY MODIFIED_ON ASC;
A_LAB,DESCRIPTION,LOCATION,DESCRIPTION,Closed,SELECT DISTINCT PARENT_LOCATION FROM LOCATION ORDER BY MODIFIED_ON ASC;
A_LAB,GROUP_ID,LOCATION,GROUP_ID,Closed,SELECT DISTINCT PARENT_LOCATION FROM LOCATION ORDER BY MODIFIED_ON ASC;
A_LAB,IDENTITY,LOCATION,IDENTITY,Closed,SELECT DISTINCT PARENT_LOCATION FROM LOCATION ORDER BY MODIFIED_ON ASC;
A_LAB,MODIFIABLE,LOCATION,MODIFIABLE,Closed,SELECT DISTINCT PARENT_LOCATION FROM LOCATION ORDER BY MODIFIED_ON ASC;
A_LAB,MODIFIED_BY,LOCATION,MODIFIED_BY,Closed,SELECT DISTINCT PARENT_LOCATION FROM LOCATION ORDER BY MODIFIED_ON ASC;
A_LAB,MODIFIED_ON,LOCATION,MODIFIED_ON,Closed,SELECT DISTINCT PARENT_LOCATION FROM LOCATION ORDER BY MODIFIED_ON ASC;
A_LAB,REMOVEFLAG,LOCATION,REMOVEFLAG,Closed,SELECT DISTINCT PARENT_LOCATION FROM LOCATION ORDER BY MODIFIED_ON ASC;
A_MLP_COMP_LIMIT,ANALYSIS_ID,A_MLP_COMP_LIMIT,ANALYSIS_ID,Obselete,null
A_MLP_COMP_LIMIT,COMPONENT_NAME,A_MLP_COMP_LIMIT,COMPONENT_NAME,Obselete,null
A_MLP_COMP_LIMIT,ORDER_NUMBER,null,null,Obselete,No Mapping
A_MLP_COMP_LIMIT,PRODUCT_ID,null,null,Obselete,No Mapping
A_MLP_COMP_LIMIT,PRODUCT_VERSION,null,null,Obselete,No Mapping
A_MLP_COMP_LIMIT,TEXT_SPEC,null,null,Obselete,No Mapping
A_MLP_COMP_LIMIT,UNITS,null,null,Obselete,No Mapping

In [0]:
#input_excel=spark.read.format("com.crealytics.spark.excel").option("header","true").option("inferSchema","true").load(read)

In [0]:
df.show()

+-------------------+--------------+---------------------+---------------------+--------------------+--------------------+
|Object name 2004 R2|    Field Name|LIMS 12.3 Object Name|LIMS 12.3 Column Name|              Status|      Comments/Query|
+-------------------+--------------+---------------------+---------------------+--------------------+--------------------+
|         A_BUILDING|        A_SITE|             LOCATION|      PARENT_LOCATION|              Closed|SELECT DISTINCT P...|
|         A_BUILDING|   DESCRIPTION|             LOCATION|          DESCRIPTION|              Closed|SELECT DISTINCT P...|
|         A_BUILDING|      GROUP_ID|             LOCATION|             GROUP_ID|              Closed|SELECT DISTINCT P...|
|         A_BUILDING|      IDENTITY|             LOCATION|             IDENTITY|              Closed|SELECT DISTINCT P...|
|         A_BUILDING|    MODIFIABLE|             LOCATION|           MODIFIABLE|              Closed|SELECT DISTINCT P...|
|         A_BUILDING|   MODIFIED_BY|             LOCATION|          MODIFIED_BY|              Closed|SELECT DISTINCT P...|
|         A_BUILDING|   MODIFIED_ON|             LOCATION|          MODIFIED_ON|              Closed|SELECT DISTINCT P...|
|         A_BUILDING|    REMOVEFLAG|             LOCATION|           REMOVEFLAG|              Closed|SELECT DISTINCT P...|
|  A_ERD_SP_BUILDING|      BUILDING|                 null|                 null|Consolidation not...|          No Mapping|
|  A_ERD_SP_BUILDING|    ERD_OFFSET|                 null|                 null|Consolidation not...|          No Mapping|
|  A_ERD_SP_BUILDING|    REMOVEFLAG|                 null|                 null|Consolidation not...|          No Mapping|
|  A_ERD_SP_BUILDING|SAMPLING_POINT|                 null|                 null|Consolidation not...|          No Mapping|
|              A_LAB|    A_BUILDING|             LOCATION|      PARENT_LOCATION|              Closed|SELECT DISTINCT P...|
|              A_LAB|   DESCRIPTION|             LOCATION|          DESCRIPTION|              Closed|SELECT DISTINCT P...|
|              A_LAB|      GROUP_ID|             LOCATION|             GROUP_ID|              Closed|SELECT DISTINCT P...|
|              A_LAB|      IDENTITY|             LOCATION|             IDENTITY|              Closed|SELECT DISTINCT P...|
|              A_LAB|    MODIFIABLE|             LOCATION|           MODIFIABLE|              Closed|SELECT DISTINCT P...|
|              A_LAB|   MODIFIED_BY|             LOCATION|          MODIFIED_BY|              Closed|SELECT DISTINCT P...|
|              A_LAB|   MODIFIED_ON|             LOCATION|          MODIFIED_ON|              Closed|SELECT DISTINCT P...|
|              A_LAB|    REMOVEFLAG|             LOCATION|           REMOVEFLAG|              Closed|SELECT DISTINCT P...|
+-------------------+--------------+---------------------+---------------------+--------------------+--------------------+
only showing top 20 rows

In [0]:
df.select('Status','Object name 2004 R2','`LIMS 12.3 Object Name`','Comments/Query','Field Name').show()

+--------------------+-------------------+---------------------+--------------------+--------------+
|              Status|Object name 2004 R2|LIMS 12.3 Object Name|      Comments/Query|    Field Name|
+--------------------+-------------------+---------------------+--------------------+--------------+
|              Closed|         A_BUILDING|             LOCATION|SELECT DISTINCT P...|        A_SITE|
|              Closed|         A_BUILDING|             LOCATION|SELECT DISTINCT P...|   DESCRIPTION|
|              Closed|         A_BUILDING|             LOCATION|SELECT DISTINCT P...|      GROUP_ID|
|              Closed|         A_BUILDING|             LOCATION|SELECT DISTINCT P...|      IDENTITY|
|              Closed|         A_BUILDING|             LOCATION|SELECT DISTINCT P...|    MODIFIABLE|
|              Closed|         A_BUILDING|             LOCATION|SELECT DISTINCT P...|   MODIFIED_BY|
|              Closed|         A_BUILDING|             LOCATION|SELECT DISTINCT P...|   MODIFIED_ON|
|              Closed|         A_BUILDING|             LOCATION|SELECT DISTINCT P...|    REMOVEFLAG|
|Consolidation not...|  A_ERD_SP_BUILDING|                 null|          No Mapping|      BUILDING|
|Consolidation not...|  A_ERD_SP_BUILDING|                 null|          No Mapping|    ERD_OFFSET|
|Consolidation not...|  A_ERD_SP_BUILDING|                 null|          No Mapping|    REMOVEFLAG|
|Consolidation not...|  A_ERD_SP_BUILDING|                 null|          No Mapping|SAMPLING_POINT|
|              Closed|              A_LAB|             LOCATION|SELECT DISTINCT P...|    A_BUILDING|
|              Closed|              A_LAB|             LOCATION|SELECT DISTINCT P...|   DESCRIPTION|
|              Closed|              A_LAB|             LOCATION|SELECT DISTINCT P...|      GROUP_ID|
|              Closed|              A_LAB|             LOCATION|SELECT DISTINCT P...|      IDENTITY|
|              Closed|              A_LAB|             LOCATION|SELECT DISTINCT P...|    MODIFIABLE|
|              Closed|              A_LAB|             LOCATION|SELECT DISTINCT P...|   MODIFIED_BY|
|              Closed|              A_LAB|             LOCATION|SELECT DISTINCT P...|   MODIFIED_ON|
|              Closed|              A_LAB|             LOCATION|SELECT DISTINCT P...|    REMOVEFLAG|
+--------------------+-------------------+---------------------+--------------------+--------------+
only showing top 20 rows

In [0]:
Amgen_access = ["111111","222222","333333","444444","555555","666666"]

# Restart Funtion 

def restart():
     a = (input("To restart enter 1 OR to exit enter 0 : "))
     if(a=="1"):
         chatbot()
     elif(a=="0"):
         print("Thank you for visiting!!!")
     else:
         print("No input found")
         restart()

# Chatbot

def chatbot():
    print("----------------------------------------------")
    print("            WELCOME TO COGNIZANT !            ")
    print("   WELCOME TO LIMS FITCAP QUICK REFERENCE     ")
    print("          AMGEN 'GEN CPLAY' CHATBOT           ")
    print("----------------------------------------------")
    name = str(input("Enter your Name: "))
    id = str(input("Enter Employee ID: "))
    if(id in Amgen_access):
        print("----------------------------------------------")
        print("| Level of Comparison                : CODE  |")
        print("|--------------------------------------------|")
        print("| Single Table Level Comparison      : STLC  |")
        print("| Multi Table Level Comparison       : MTLC  |")
        print("| Row Level Comparison               : RLC   |")
        print("----------------------------------------------")
        print("Please select Level of Comparison - please Enter respective code")
        Q_ask = input().upper()
        

# single-table level comparison    

     
        '''if(Q_ask == "STLC"):
            single_table_name = input("Enter the table name : ").upper()
            rows1 = df[(df['Object name 2004 R2'] == single_table_name)]
            rows1 = rows1[['Object name 2004 R2', 'Field Name', '`LIMS 12.3 Object Name`', '`LIMS 12.3 Column Name`', 'Comments/Query']]
            if rows1.empty():
                print(f"{single_table_name} not found in the data.")
            else:
                rows1.show()
            restart()'''
        if(Q_ask == "STLC"):
           single_table_name = input("Enter the table name : ").upper()
           rows1 = df.filter(df['Object name 2004 R2'] == single_table_name)
           rows1 = rows1.select(
                "Object name 2004 R2",
                "Field Name",
                "`LIMS 12.3 Object Name`",
                "`LIMS 12.3 Column Name`",
                "Comments/Query")
           if rows1.count() == 0:
                print(f"{single_table_name} not found in the data.")
           else:
                #display(rows1)
                rows1.show()
           restart()
        
        
# multi-table level comparison


        elif(Q_ask == "MTLC"):
            multi_table_name_list = input("Enter multiple Table names separated by space: ").upper().split()
            for i in multi_table_name_list:    
                rows2 = df.filter(df['Object name 2004 R2'] == i)
                rows2 = rows2.select('Object name 2004 R2', 'Field Name', '`LIMS 12.3 Object Name`', '`LIMS 12.3 Column Name`',        'Comments/Query')
                if rows2.count()==0:
                    print(f"{multi_table_name_list} one or more table not found in the data.")
                else:
                    rows2.show()
            restart()
        
        
 # row level comparison 

      
        elif(Q_ask == "RLC"):
            print("-----------------------------------------------------------------")
            print("Enter 2004 R2 table name and column name separated by a dot (.): ")
            print("e.g. tablename.columnname")
            input_str = str(input()).upper()
            input1, input2 = input_str.split(".")
            input1 = str(input1)
            input2 = str(input2)
             
            matching_rows = df.filter((df['Object name 2004 R2'] == input1) & (df['Field Name'] == input2))
            if matching_rows.count() == 0:
                print("Such table or column does not exist !")
                restart()
            else:
                data_row = matching_rows.first()
                #if input1 in df.select('Object name 2004 R2').distinct().collect():
                    #if input2 in df.select('Field Name').distinct().collect():
                if df.filter(df['Object name 2004 R2'] == input1).count() > 0:
                    if df.filter(df['Field Name'] == input2).count() > 0:
                        if "Closed" in data_row['Status']:
                
                            print("-------------------------------------------------------------------------------------------")
                            print("Following is the LIMS 12.3 Object Name and LIMS 12.3 Column Name for the respective input: ")
                            print(data_row['LIMS 12.3 Object Name'] + "." + data_row['LIMS 12.3 Column Name'])
                            print("-------------------------------------------------------------------------------------------")
                            print("Comments / Query - ")
                            print(data_row['Comments/Query'])
                            restart()
                        elif "Consolidation not required" in data_row['Status']:
                            print("Reference object not available in LIMS 12.3")
                            print("-------------------------------------------------------------------------------------------")
                            print("Comments / Query - ")
                            print(data_row['Comments/Query'])
                            restart()
                        elif input1 == "A_MLP_COMP_LIMIT" and input2 == "ANALYSIS_ID":
                            print("-------------------------------------------------------------------------------------------")
                            print("Following is the LIMS 12.3 Object Name and LIMS 12.3 Column Name for the respective input: ")
                            print(data_row['LIMS 12.3 Object Name'] + "." + data_row['LIMS 12.3 Column Name'])
                            print("-------------------------------------------------------------------------------------------")
                            print("Comments / Query - ")
                            print(data_row['Comments/Query'])
                            restart()
                        elif input1 == "A_MLP_COMP_LIMIT" and input2 == "COMPONENT_NAME":
                            print("-------------------------------------------------------------------------------------------")
                            print("Following is the LIMS 12.3 Object Name and LIMS 12.3 Column Name for the respective input: ")
                            print(data_row['LIMS 12.3 Object Name'] + "." + data_row['LIMS 12.3 Column Name'])
                            print("-------------------------------------------------------------------------------------------")
                            print("Comments / Query - ")
                            print(data_row['Comments/Query'])
                            restart()
                        elif "Obselete" in data_row['Status']:
                            print("No reference to the column in LIMS 12.3")
                            print("-------------------------------------------------------------------------------------------")
                            print("Comments / Query - ")
                            print(data_row['Comments/Query'])
                            restart()
                        else:
                            print("Status not updated ! Please try later")
                            restart()
                    else:
                        print("No such row data found")
                        restart()
                else:
                    print("No such table data found")
                    restart()
        else:
            print("Invalid input ! Please restart session")
            restart()
    else:
        print("Access Denied !!!")
        restart()

           
chatbot()

----------------------------------------------
            WELCOME TO COGNIZANT !
   WELCOME TO LIMS FITCAP QUICK REFERENCE
          AMGEN 'GEN CPLAY' CHATBOT
----------------------------------------------

Enter your Name:  ravi

Enter Employee ID:  222222

----------------------------------------------
| Level of Comparison                : CODE  |
|--------------------------------------------|
| Single Table Level Comparison      : STLC  |
| Multi Table Level Comparison       : MTLC  |
| Row Level Comparison               : RLC   |
----------------------------------------------
Please select Level of Comparison - please Enter respective code

 STLC

Enter the table name :  a_building

+-------------------+-----------+---------------------+---------------------+--------------------+
|Object name 2004 R2| Field Name|LIMS 12.3 Object Name|LIMS 12.3 Column Name|      Comments/Query|
+-------------------+-----------+---------------------+---------------------+--------------------+
|         A_BUILDING|     A_SITE|             LOCATION|      PARENT_LOCATION|SELECT DISTINCT P...|
|         A_BUILDING|DESCRIPTION|             LOCATION|          DESCRIPTION|SELECT DISTINCT P...|
|         A_BUILDING|   GROUP_ID|             LOCATION|             GROUP_ID|SELECT DISTINCT P...|
|         A_BUILDING|   IDENTITY|             LOCATION|             IDENTITY|SELECT DISTINCT P...|
|         A_BUILDING| MODIFIABLE|             LOCATION|           MODIFIABLE|SELECT DISTINCT P...|
|         A_BUILDING|MODIFIED_BY|             LOCATION|          MODIFIED_BY|SELECT DISTINCT P...|
|         A_BUILDING|MODIFIED_ON|             LOCATION|          MODIFIED_ON|SELECT DISTINCT P...|
|         A_BUILDING| REMOVEFLAG|             LOCATION|           REMOVEFLAG|SELECT DISTINCT P...|
+-------------------+-----------+---------------------+---------------------+--------------------+

To restart enter 1 OR to exit enter 0 :  sanket

No input found

To restart enter 1 OR to exit enter 0 :  1

----------------------------------------------
            WELCOME TO COGNIZANT !
   WELCOME TO LIMS FITCAP QUICK REFERENCE
          AMGEN 'GEN CPLAY' CHATBOT
----------------------------------------------

Enter your Name:  sanket

Enter Employee ID:  111111

----------------------------------------------
| Level of Comparison                : CODE  |
|--------------------------------------------|
| Single Table Level Comparison      : STLC  |
| Multi Table Level Comparison       : MTLC  |
| Row Level Comparison               : RLC   |
----------------------------------------------
Please select Level of Comparison - please Enter respective code

 MTLC

Enter multiple Table names separated by space:  a_building a_lab

+-------------------+-----------+---------------------+---------------------+--------------------+
|Object name 2004 R2| Field Name|LIMS 12.3 Object Name|LIMS 12.3 Column Name|      Comments/Query|
+-------------------+-----------+---------------------+---------------------+--------------------+
|         A_BUILDING|     A_SITE|             LOCATION|      PARENT_LOCATION|SELECT DISTINCT P...|
|         A_BUILDING|DESCRIPTION|             LOCATION|          DESCRIPTION|SELECT DISTINCT P...|
|         A_BUILDING|   GROUP_ID|             LOCATION|             GROUP_ID|SELECT DISTINCT P...|
|         A_BUILDING|   IDENTITY|             LOCATION|             IDENTITY|SELECT DISTINCT P...|
|         A_BUILDING| MODIFIABLE|             LOCATION|           MODIFIABLE|SELECT DISTINCT P...|
|         A_BUILDING|MODIFIED_BY|             LOCATION|          MODIFIED_BY|SELECT DISTINCT P...|
|         A_BUILDING|MODIFIED_ON|             LOCATION|          MODIFIED_ON|SELECT DISTINCT P...|
|         A_BUILDING| REMOVEFLAG|             LOCATION|           REMOVEFLAG|SELECT DISTINCT P...|
+-------------------+-----------+---------------------+---------------------+--------------------+

+-------------------+-----------+---------------------+---------------------+--------------------+
|Object name 2004 R2| Field Name|LIMS 12.3 Object Name|LIMS 12.3 Column Name|      Comments/Query|
+-------------------+-----------+---------------------+---------------------+--------------------+
|              A_LAB| A_BUILDING|             LOCATION|      PARENT_LOCATION|SELECT DISTINCT P...|
|              A_LAB|DESCRIPTION|             LOCATION|          DESCRIPTION|SELECT DISTINCT P...|
|              A_LAB|   GROUP_ID|             LOCATION|             GROUP_ID|SELECT DISTINCT P...|
|              A_LAB|   IDENTITY|             LOCATION|             IDENTITY|SELECT DISTINCT P...|
|              A_LAB| MODIFIABLE|             LOCATION|           MODIFIABLE|SELECT DISTINCT P...|
|              A_LAB|MODIFIED_BY|             LOCATION|          MODIFIED_BY|SELECT DISTINCT P...|
|              A_LAB|MODIFIED_ON|             LOCATION|          MODIFIED_ON|SELECT DISTINCT P...|
|              A_LAB| REMOVEFLAG|             LOCATION|           REMOVEFLAG|SELECT DISTINCT P...|
+-------------------+-----------+---------------------+---------------------+--------------------+

To restart enter 1 OR to exit enter 0 :  1

----------------------------------------------
            WELCOME TO COGNIZANT !
   WELCOME TO LIMS FITCAP QUICK REFERENCE
          AMGEN 'GEN CPLAY' CHATBOT
----------------------------------------------

Enter your Name:  aditya

Enter Employee ID:  333333

----------------------------------------------
| Level of Comparison                : CODE  |
|--------------------------------------------|
| Single Table Level Comparison      : STLC  |
| Multi Table Level Comparison       : MTLC  |
| Row Level Comparison               : RLC   |
----------------------------------------------
Please select Level of Comparison - please Enter respective code

 RLC

-----------------------------------------------------------------
Enter 2004 R2 table name and column name separated by a dot (.):
e.g. tablename.columnname

 a_building.a_site

-------------------------------------------------------------------------------------------
Following is the LIMS 12.3 Object Name and LIMS 12.3 Column Name for the respective input:
LOCATION.PARENT_LOCATION
-------------------------------------------------------------------------------------------
Comments / Query -
SELECT DISTINCT PARENT_LOCATION
FROM LOCATION
ORDER BY GROUP_ID DESC;

To restart enter 1 OR to exit enter 0 :